//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelMgtSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_details
    {
        public int staff_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string other_name { get; set; }
        public string phone_no { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string user_previledge { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
