//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelMgtSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student_details()
        {
            this.visitor_details = new HashSet<visitor_details>();
        }
    
        public int student_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string other_name { get; set; }
        public string nationalty { get; set; }
        public string phone_no { get; set; }
        public Nullable<int> room_id { get; set; }
        public string room_no { get; set; }
        public Nullable<System.DateTime> time_in { get; set; }
        public Nullable<System.DateTime> time_out { get; set; }
    
        public virtual room_details room_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_details> visitor_details { get; set; }
    }
}
