//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelMgtSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor_details
    {
        public int visitor_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string other_name { get; set; }
        public string address { get; set; }
        public string phone_no { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public string room_no { get; set; }
        public Nullable<System.DateTime> time_in { get; set; }
        public Nullable<System.DateTime> time_out { get; set; }
    
        public virtual room_details room_details { get; set; }
        public virtual student_details student_details { get; set; }
    }
}
